fix: bump jackson-dataformat-yaml to fix build (#39)
Maven build was failing due to `java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/JacksonFeature`. Bumped `jackson-dataformat-yaml` to `2.14.2`.